export {default as adminController} from './auth/adminController'
export {default as teacherController} from './auth/teacherController'
export {default as parentController} from './auth/parentController'
export {default as classController} from './auth/classController'
export {default as studentController} from './auth/studentController'